authors:
  aborgardt:
    name: Alexander Borgardt
    description: Software Engineer, Nerd, Gamer ... and Blogger?
    avatar: https://avatars.githubusercontent.com/u/5030347?v=4
    url: http://alexander.borgardt.me
